### ISSUE TITLE
MultiShot event registration

### ISSUE THREAD

**Issue by andrewthad** [andrewthad/sockets#11]
This could be a pretty big performance win. The GHC event manager allows you to register both single-shot and a multi-shot events. Multi-shot, which is sadly buried away in internal modules, is probably a better choice for everything in `sockets`. Instead of repeatedly registering interest in the same file descriptor over and over again, we could just register once and then have the event manager fill an `MVar` every time that happens. As a part of the [an manager allocations improvement](https://gitlab.haskell.org/ghc/ghc/merge_requests/313), I'm going to try to expose a decent interface for multi-shot event registration.

**Comment by chessai** [comment]
dope

**Comment by andrewthad** [comment]
This is an even bigger win than I originally thought. Currently, there are several places where we do the "send, check for EWOULDBLOCK, possibly register with event manager and wait and send again" dance. This is tedious and a little error-prone. With the multishot event manager, there's no penalty for just doing the waiting upfront since we are already registered the whole time. Just blocking on the STM transaction (or an MVar) from the beginning is fine since it's so cheap (cheaper than the syscall).

**Comment by andrewthad** [comment]
This is going to require committing to the threaded runtime. That is, no support for the non-threaded runtime. (Well, technically, it could support the non-threaded runtime, but it would be tedious and likely unused).

**Comment by andrewthad** [comment]
And I just thought of a tricky annoyance that shows up. Currently, we have:

    newtype Connection = Connection Fd
    connect :: Endpoint -> IO (Either (ConnectException Uninterruptible) Connection)

With a multishot registration, we would need:

    data Connection = Connection !Fd !(TVar Bool)
    connect :: Endpoint -> IO (Either (ConnectException Uninterruptible) (Connection,Unique))

We need the `Unique` to build the `FdKey` that we use to unregister interest with `unregisterFd`. The type signature of `withConnection` however, remains unchanged.

**Comment by andrewthad** [comment]
This has been accomplished my writing a custom event manager.
