### ISSUE TITLE
withConnection type 

### ISSUE THREAD

**Issue by mitchellwrosen** [andrewthad/sockets#12]
The type of `withConnection` makes it difficult to diagnose errors:

```haskell
withConnection :: 
     Endpoint	
  -> (Connection -> IO a)	
  -> IO (Either SocketException a)
```

If I get an `errno` out of this, I can't tell if it was due to the initial connection (e.g. ECONNREFUSED), or during graceful teardown (e.g. ENOTCONN).

**Comment by mitchellwrosen** [comment]
Well, the example errnos I gave are bad because you will not get an ECONNREFUSED during teardown, nor an ENOTCONN before the connection is established. But surely some errnos overlap between connecting and disconnecting.

**Comment by andrewthad** [comment]
When I address https://github.com/andrewthad/sockets/issues/8, I should be able to fix this at the same time, interpreting the error codes and naming these expected exceptions in a way that makes their context clear.

**Comment by mitchellwrosen** [comment]
Excellent, I look forward to seeing what you come up with.
