### ISSUE TITLE
Interruptible connect

### ISSUE THREAD

**Issue by mitchellwrosen** [andrewthad/sockets#14]
The docs for `ConnectTimeout` say:

```
Users interested in timing out more quickly are encouraged to use registerDelay with the
interruptible variants of the connection functions in this library. (ETIMEDOUT)
```

but there isn't an interruptible `withConnection` variant (yet?)

**Comment by andrewthad** [comment]
I haven't tested these yet, but aec2007fa36d939cb205ead7468b3e282100f5ab should address this.

**Comment by mitchellwrosen** [comment]
That was fast, thanks!

**Comment by mitchellwrosen** [comment]
Works great :+1:
