### ISSUE TITLE
SocketUnrecoverableException

### ISSUE THREAD

**Issue by mitchellwrosen** [andrewthad/sockets#15]
Just saw this one:

```
SocketUnrecoverableException {modules = "Socket.Stream.IPv4", function = "internalReceiveMaximally", description = ["error code 9"]}
```

**Comment by mitchellwrosen** [comment]
Ah, this is `EBADF`, I think I might be accidentally using a socket after closing it.

**Comment by andrewthad** [comment]
At the least though, I should make some attempt to backtranslate the error codes into their actual names (that is, display `EBADF` in the error message). This would help make things more clear in this situation.

**Comment by andrewthad** [comment]
Out of curiosity, how did you manage to use the socket after closing it? The bracket pattern used in `sockets` makes it difficult, but not impossible, for this to happen.

**Comment by andrewthad** [comment]
The error message should be improved slightly by 515b5d714c9d6f2b5ce3492321d9e745d0c8b2e7. At least, it makes it more immediately clear to the user that their dealing with `EBADF`.

**Comment by mitchellwrosen** [comment]
> Out of curiosity, how did you manage to use the socket after closing it?

In my Riak client library I have a "managed socket" abstraction that opens a socket, smuggles it to the outside world in a TMVar for normal send/recv usage, then handles health checking, idle timeout, and reconnect on failure. So the bracket pattern unfortunately doesn't help me manage the connection's life cycle. :(

**Comment by mitchellwrosen** [comment]
I just encountered an odd Riak behavior where during startup, it may accept a request, and then simply never respond. So I swapped some code around to use the `interruptible` flavors of recv with `registerDelay` and now everything works perfectly. You've designed a very nice API, kudos @andrewthad!

**Comment by andrewthad** [comment]
Great to hear that it's working well! Concerning the use in your riak client where the bracket pattern doesn't work, I've been adding [unbracketed functions](http://hackage.haskell.org/package/sockets-0.3.0.0/docs/Socket-Stream-IPv4.html#g:5) to handle this kind of situation. It's possible that I don't yet have all the ones you need available, but let me know if there are others that you need. Smuggling out the resource scoped by a bracketing function is confusing to readers of code and a source of bugs for authors of code. I'd like to expose enough primitives that hacks like this become unnecessary.

**Comment by mitchellwrosen** [comment]
> Smuggling out the resource scoped by a bracketing function is confusing to readers of code and a source of bugs for authors of code. I'd like to expose enough primitives that hacks like this become unnecessary.

I spent a while thinking about this. In my design, a background thread (quite like an Erlang actor) was responsible for opening the connection, and reacting to relevant events: a request on the socket failed (so we should close it and reconnect), a health check failed (so we should start rejecting clients while we wait for the connection to repair), idle timeout (so we should close it and not reconnect), etc.

In this case it didn't really matter whether the background thread used `withConnection` or explicit `connect`/`disconnect` calls, because it was still the case that the life cycle of the socket was managed by a completely separate part of the code. So `withConnection` was actually _safer_, and preferred, and smuggling the connection out of a `TVar` was unavoidable.

However I do completely agree that the code was hard to read and understand, and basically violated the expectations of a normal callback-style resource acquisition. So I completely refactored it to be more "egalitarian", that is, any client that comes along and tries to use a socket is equally responsible for helping manage its life cycle.

I think what I've got now is even _harder_ to understand, because it involves so much very careful exception masking and precise STM timings, blackholing TVars... some of the complexity is due to the domain (Riak can handle concurrent, pipelined requests) but I must admit I'm rather horrified of my own creation; it's extremely hard to test and probably _riddled_ with concurrency bugs.

https://github.com/mitchellwrosen/riak2/blob/01931cc41f59e476c4c8b2721b9aa0dd8b55ca11/riak2/src/RiakManagedBus.hs

Over time I hope to refactor, simplify, and figure out how to test this, but my current thinking is that resource management in Haskell is just really hard.

**Comment by andrewthad** [comment]
If I understand correctly, there's only one socket open at a time. Is the state machine that you outlined at the top of the file something you came up with, or is it something the riak documentation recommends for clients? Either way, it's rather helpful that you have it there with the code.

The only thing I can think of that would help reason about concurrency would be to keep all state-machine-transitioning logic on its own thread. The way clients currently interacts with the state machine is that "any client that comes along and tries to use a socket is equally responsible for helping manage its life cycle". This forces you to think about asynchronous exceptions during the transitions. But if all the transitioning logic is on one thread and the corresponding `ThreadId` is not exposed by the abstraction you provide, the thread cannot receive asynchronous exceptions. If any exception ever happens on the thread, it's a mistake in the library.

If you did this, you would need a way to communicate with the state-machine-transitioning thread. This would be done with standard concurrency primitives, pairing two `MVar`s for each possible typed request-response pair.

But I'm not sure if what I suggested will work well. Concurrent-request pipelining seems difficult to do. I wonder if there are other implementations of other protocols that provide a good example of what this looks like.

**Comment by mitchellwrosen** [comment]
Yeah, this file that I linked only manages a single socket (the actual "riak handle" is a pool of these). The state machine is just something I came up with and am refining further.

> The only thing I can think of that would help reason about concurrency would be to keep all state-machine-transitioning logic on its own thread.

This is somewhat like the previous version of the code I alluded to - a "manager thread" was authoritative over the state of the socket. However, unless I misunderstood your first (or latest) comment, this basically required calling `withConnection`, smuggling the alive connection out via a shared variable, and "staying in" the callback waiting for something to happen (while keeping the connection alive). The control flow was just weird.

> The way clients currently interacts with the state machine is that "any client that comes along and tries to use a socket is equally responsible for helping manage its life cycle". This forces you to think about asynchronous exceptions during the transitions. But if all the transitioning logic is on one thread and the corresponding ThreadId is not exposed by the abstraction you provide, the thread cannot receive asynchronous exceptions. If any exception ever happens on the thread, it's a mistake in the library.

I love the idea of forking a background thread, tossing its `ThreadId` and therefore guaranteeing that it will never be thrown a `ThreadKilled`. I believe the only exception it might ever receive from the runtime is `StackOverflow` which, well, is another bug that I'll just have to be careful not to introduce. But this technique, combined with the excellent `sockets` code underneath that itself is very careful not to throw any synchronous exception, makes me less paranoid about my "ghost threads" accidentally dying and bringing the program to a completely nonsense, bonkers broken state. And it does require careful exception masking when forking threads from untrusted code, as you mention.

There are other Riak-isms influencing the design of this code (such as it disallowing any requests while it's currently "streaming" a response out), but I am trying to find a simple, grokkable "core" abstraction to describe what's going on here. And overall I'm satisfied with the explicit `connect`/`disconnect` design, Thanks for taking a look!

**Comment by andrewthad** [comment]
Cool. Thanks for explaining the different approaches you've taken and the trade offs they had. This is certainly a tricky problem domain, and it's not something I've ever had to deal with, but I've enjoyed looking at and hearing about what you've done. Best of luck on it.

Also, I couldn't stop thinking about this last night, so I wrote up a [minimal example](https://gist.github.com/andrewthad/12f1f2d1e5a00ced9e9f24e8f573b3f6) that captures the essence of the worker-thread pattern. It's mostly so that I don't forget what I've learned from this conversation, but I thought you might enjoy it too.

**Comment by mitchellwrosen** [comment]
Interesting, thanks! I think this may be solving a slightly different problem (resource starvation), since in my case, all client threads of a Riak handle do not have access to the underlying connection directly, instead they must go through the master "exchange" function:

```
exchange socket request = do
  send request socket
  receive socket
```

So it's really not possible to hold onto the socket for too long, a client cannot do anything between sending and receiving (ignoring streaming requests, which summarize the response in IO with a `FoldM IO Response`).
 
However, I do like the idea of using dedicated worker threads for all socket sending and receiving. Currently, I do not:

https://github.com/mitchellwrosen/riak2/blob/01931cc41f59e476c4c8b2721b9aa0dd8b55ca11/riak2/src/RiakBus.hs

I have some complicated "baton passing" idea somewhere in there, wherein I endeavor to hold a lock on the socket only for the `send` half of the exchange (because requests can be pipelined), and then release the lock (but not before mutating some other state so that we're first in line to receive the reply that corresponds to our request).

Another concern I had/have is determining what code is responsible for decoding replies. In theory the code closest to the underlying socket only needs to pull packets off the wire, not waste CPU cycles doing protobuf decoding (to increase raw throughput). However, that then requires some other messaging mechanism for informing a socket, "hey, I received garbage data on you, you're messed up now, please close".
