### ISSUE TITLE
Rename Send and Receive Functions

### ISSUE THREAD

**Issue by andrewthad** [andrewthad/sockets#22]
The names in this library are getting unwieldy. From `Socket.Stream.IPv4`:

```
  , sendByteArray
  , sendByteArraySlice
  , sendMutableByteArray
  , sendMutableByteArraySlice
  , sendAddr
  , sendByteString
  , sendLazyByteString
  , interruptibleSendByteArray
  , interruptibleSendByteArraySlice
  , interruptibleSendMutableByteArraySlice
  , receiveByteArray
  , receiveBoundedByteArray
  , receiveBoundedMutableByteArraySlice
  , receiveMutableByteArray
  , receiveByteString
  , interruptibleReceiveByteArray
  , interruptibleReceiveBoundedMutableByteArraySlice
```

Some of these are pretty long. We currently have the following distinctions:

- bounded/fixed-length (and also between-length on master)
- sliced/unsliced
- interruptible/uninterruptible
- ByteArray/MutableByteArray/Addr/ByteString

The solution is to use the module system. The question is how much. We could do one module per unique combination of these, but that puts us at 3*2*2*4=48 modules, so that's not a great option. We could drop the sliced/unsliced distinction entirely and only provide the sliced variants. I'm inclined to do this since these are often what the user wants anyway. The two tempting ways to break things out into modules are the interruptible/uninterruptible axis and the ByteArray/MutableByteArray/Addr/ByteString axis. Doing both gives us eight modules, which feels like a lot. I think splitting on interruptibility is a good bet since users should not really ever be mixing the interruptible and uninterruptible variants. What if we collapsed `MutableByteArray` and `ByteArray` ops into the same module since it's conceivable that these would be used together? How about:

```
Socket
  Stream
    IPv4
      ByteArray
        Interruptible (send,sendMutable,receive,receiveMutable,receiveBounded,receiveBoundedMutable,receiveBetween,receiveBetweenMutable)
        Uninterruptible (send,sendMutable,receive,receiveMutable,receiveBounded,receiveBoundedMutable,receiveBetween,receiveBetweenMutable)
      Addr
        Interruptible (send,receive,receiveBounded,receiveBetween)
        Uninterruptible (send,receive,receiveBounded,receiveBetween)
      ByteString
        Interruptible (send,receive,receiveBounded,receiveBetween)
        Uninterruptible (send,receive,receiveBounded,receiveBetween)
```

This gives six modules total, and users are unlikely to need more than one of them in the same project. Another bikeshedding thought is that, with the names being shorter, it may be good to rename `receive` to `receiveExactly`. It's not terribly intuitive that `receive` can make multiple `recv` calls to pull multiple chunks off the receive buffer.

**Comment by mitchellwrosen** [comment]
Is backpack at all an option, to provide a uniform API for `ByteArray`/`ByteString`/`Addr`? Then there could just be

```
Socket
  Stream
    IPv4
      Interruptible
      Uninterruptible
```

**Comment by chessai** [comment]
i love backpack but it doesn't play well with stack and nix:

https://github.com/commercialhaskell/stack/issues/2540

https://www.reddit.com/r/haskell/comments/8hgpte/problem_using_nix_when_dependencies_use_backpack/

https://github.com/NixOS/nixpkgs/issues/40128

**Comment by andrewthad** [comment]
One issue with the use of backpack that you suggest is that according to your suggestion, this library would provide the `Interruptible` and `Uninterruptible` indefinite modules, putting the burden of instantiating them on the user (and also making things not work for users of stack or nix). And there are a very small number of possible instantiations. But even if `sockets` were just going to do the instantiations internally, another even bigger problem is that `receive` doesn't even have a consistent type signature across different buffer types. Slicing is built in to `ByteString` and is halfway built in to `Addr` (because of `plusAddr`). And for mutable types, the reception buffer is in argument position, not result position. More visually:

```
recv :: MutableByteArray RealWorld -> Int -> Int -> IO (Either E ())
recv :: Addr -> Int -> IO (Either E ())
recv :: Int -> IO (Either E ByteArray)
recv :: Int -> IO (Either E ByteString)

send :: MutableByteArray RealWorld -> Int -> Int -> IO (Either E ())
send :: Addr -> Int -> Int -> IO (Either E ())
send :: ByteArray -> Int -> Int -> IO (Either E ())
send :: ByteString -> IO (Either E ())
```

This problem thwarts attempts to use typeclasses or backpack. There unfortunately isn't really a terribly uniform interface to this stuff across different buffer types. I somewhat interested in using backpack internally to reduce duplication:

* `send` really is almost the same across all four types
* Interruptible and uninterruptible variants of functions are almost the same
* It's possible to share some of the `recv` code with a clever backpack signature

[According to Edward Yang](https://github.com/commercialhaskell/stack/issues/2540):

> private use of Backpack (i.e., the public library does not have any signatures) should be supported out-of-the-box, as there is no change to the outward-facing API of Setup scripts in this case

However, nix appears to be in a worse position with even internal use of backpack preventing packages from building.

**Comment by chessai** [comment]
i guess it's fine since the bug in nix is actually addressed for upstream dependencies (since nix invokes the "workaround" directly). only projects using nix with cabal are messed up. the issue with stack still stands as far as i am aware, but perhaps that's okay, since sockets is not yet stable.

**Comment by andrewthad** [comment]
Simultaneous comments. Can you link a source for the nix backpack problem being partially resolved? If that's the case, it seems like we could use backpack internally and all the build tools would be happy.

**Comment by chessai** [comment]
> [According to Edward Yang](https://github.com/commercialhaskell/stack/issues/2540):
> 
> > private use of Backpack (i.e., the public library does not have any signatures) should be supported out-of-the-box, as there is no change to the outward-facing API of Setup scripts in this case
> 
> However, nix appears to be in a worse position with even internal use of backpack preventing packages from building.

nix is able to build packages on hackage that use backpack by avoiding `cabal configure` and using `runhaskell Setup.hs configure`. so, nix can build upstream dependencies that export indefinite modules (example off the top of my head: unpacked-containers)
