### ISSUE TITLE
Sliced receive buffers

### ISSUE THREAD

**Issue by haitlahcen** [andrewthad/sockets#9]
First I would like to thank you for this simple yet powerful library.

It would be great if we could pass a custom `MutableByteArray` with an `offset` and `length` to a `receiveMutableByteArraySlice` function (symmetric to `sendMutableByteArraySlice`).

This would allow us to create a giant pinned buffer, and use an offset+size per client when receiving. Hence unlocking better performance for receive operations (for instance, constant in memory if we fix the maximum number of clients in a given program).

**Comment by andrewthad** [comment]
I’m glad that you find the library useful!  I am planning on adding a receive function that works the way you describe.
